import type { Metadata, Viewport } from "next";
import { Karla, Newsreader } from "next/font/google";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { site } from "@/lib/site";
import "./globals.css";

/* --------------------------------------------------------------------------
   Fonts — self-hosted at build time by next/font. No request ever leaves the
   user's browser for a font file, and there is no layout shift on load.
   -------------------------------------------------------------------------- */

const newsreader = Newsreader({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-newsreader",
  // Variable font: the full weight range ships in one file.
});

const karla = Karla({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-karla",
});

/* --------------------------------------------------------------------------
   Metadata
   -------------------------------------------------------------------------- */

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — ${site.role}`,
    template: `%s — ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  publisher: site.name,
  keywords: [
    "Mann Cayona",
    "woven paintings",
    "woven canvas",
    "Ilonggo art",
    "Iloilo artist",
    "Tigbauan",
    "hablon",
    "patadyong",
    "Philippine contemporary art",
    "Panay Island",
  ],
  category: "art",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    siteName: site.name,
    title: `${site.name} — ${site.role}`,
    description: site.description,
    url: site.url,
    locale: site.locale,
    // The image itself is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} — ${site.role}`,
    description: site.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  formatDetection: {
    telephone: true,
    address: false,
    email: true,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // Matches --canvas-100 / --ink-950 so the browser chrome joins the page.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f5f1e8" },
    { media: "(prefers-color-scheme: dark)", color: "#14130f" },
  ],
};

/* Structured data — lets search and aggregators read the practice correctly. */
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: site.name,
  jobTitle: "Visual Artist",
  description: site.description,
  url: site.url,
  email: `mailto:${site.contact.email}`,
  telephone: site.contact.phoneHref.replace("tel:", ""),
  address: {
    "@type": "PostalAddress",
    addressLocality: site.location.city,
    addressRegion: "Iloilo",
    addressCountry: "PH",
  },
  knowsAbout: ["Woven canvas", "Oil painting", "Hablon weaving", "Ilonggo textiles"],
  sameAs: site.social.map((s) => s.href),
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en-PH"
      className={`${newsreader.variable} ${karla.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Scroll reveals ship their hidden state in the SSR HTML. Without JS
            that would leave the Process essay blank, so unwind it: reveal the
            content and drop the weave veils entirely. Author !important beats
            a non-important inline style. */}
        <noscript>
          <style>{`#process [style*="opacity"]{opacity:1!important;transform:none!important}#process .motion-veil{display:none!important}`}</style>
        </noscript>
      </head>
      <body className="flex min-h-dvh flex-col bg-background font-sans text-ink">
        <SiteNav />
        <main id="main" className="flex-1">
          {children}
        </main>
        <SiteFooter />
        <script
          type="application/ld+json"
          // Static, author-controlled object — no user input reaches this.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </body>
    </html>
  );
}
